<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Authentication\Hybrid\Doctrine\Controller;

use MSBios\Authentication\AuthenticationServiceAwareInterface;
use MSBios\Authentication\AuthenticationServiceAwareTrait;
use MSBios\Authentication\Hybrid\Controller\IndexController as DefaultIndexController;
use MSBios\Guard\GuardInterface;

/**
 * Class IndexController
 * @package MSBios\Authentication\Hybrid\Doctrine\Controller
 */
class IndexController extends DefaultIndexController implements GuardInterface, AuthenticationServiceAwareInterface
{
    use AuthenticationServiceAwareTrait;

    /**
     * @return \Zend\View\Model\ViewModel
     */
    public function indexAction()
    {
        // var_dump($this->getAuthenticationService()->getIdentity()); die();
        // echo __METHOD__; die();
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

}
