<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Authentication\Hybrid\Doctrine\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

/**
 * Class ProfileController
 * @package MSBios\Authentication\Hybrid\Doctrine\Controller
 */
class ProfileController extends AbstractActionController
{
    /**
     * @return ViewModel
     */
    public function loginAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    /**
     * @return ViewModel
     */
    public function logoutAction()
    {
        return new ViewModel;
    }

}